/* TODO: Let NTSC people have 'DKS' */
static const char dksc[] = "DKSC";
const char *track_table[] = {"MC",   "MMM",  "MG",  "GV",   "TF",  "CM",    dksc,   "WGM",
                             "LC",   "DC",   "MH",  "MT",   "BC",  "RR",    "DDR",  "KC",
                             "rPB",  "rMC",  "rWS", "rDKM", "rYF", "rDH",   "rPG",  "rDS",
                             "rMC3", "rGV2", "rMR", "rSL",  "rBC", "rDKJP", "rBC3", "rSGB"};

const unsigned int track_offset_table[] = {0x0,  0x1,  0x2,  0x3,  0x4,  0x5,  0x6,  0x7,
                                           0x8,  0x9,  0xA,  0xB,  0xC,  0xD,  0xE,  0xF,
                                           0x18, 0x1C, 0x11, 0x15, 0x14, 0x10, 0x1F, 0x1A,
                                           0x1D, 0x13, 0x16, 0x19, 0x12, 0x1E, 0x1B, 0x17};

const char *vehicle_table[] = {
        "Standard Kart S",  "Standard Kart M", "Standard Kart L", "Baby Booster",
        "Classic Dragster", "Offroader",       "Mini Beast",      "Wild Wing",
        "Flame Flyer",      "Cheep Charger",   "Super Blooper",   "Piranha Prowler",
        "Rally Romper",     "Daytripper",      "Jetsetter",       "Blue Falcon",
        "Sprinter",         "Honeycoupe",      "Standard Bike S", "Standard Bike M",
        "Standard Bike L",  "Bullet Bike",     "Mach Bike",       "Bowser Bike",
        "Bit Bike",         "Sugarscoot",      "Wario Bike",      "Quacker",
        "Zip Zip",          "Shooting Star",   "Magikruiser",     "Sneakster",
        "Torpedo",          "Jet Bubble",      "Dolphin Dasher",  "Phantom"};

const char *character_table[] = {"Mario",
                                 "Baby Peach",
                                 "Waluigi",
                                 "Bowser",
                                 "Baby Daisy",
                                 "Dry Bones",
                                 "Baby Mario",
                                 "Luigi",
                                 "Toad",
                                 "Donkey Kong",
                                 "Yoshi",
                                 "Wario",
                                 "Baby Luigi",
                                 "Toadette",
                                 "Koopa Troopa",
                                 "Daisy",
                                 "Peach",
                                 "Birdo",
                                 "Diddy Kong",
                                 "King Boo",
                                 "Bowser Jr.",
                                 "Dry Bowser",
                                 "Funky Kong",
                                 "Rosalina",
                                 "Small Mii Outfit A (Male)",
                                 "Small Mii Outfit A (Female)",
                                 "Small Mii Outfit B (Male)",
                                 "Small Mii Outfit B (Female)",
                                 "Small Mii Outfit C (Male)",
                                 "Small Mii Outfit C (Female)",
                                 "Medium Mii Outfit A (Male)",
                                 "Medium Mii Outfit A (Female)",
                                 "Medium Mii Outfit B (Male)",
                                 "Medium Mii Outfit B (Female)",
                                 "Medium Mii Outfit C (Male)",
                                 "Medium Mii Outfit C (Female)",
                                 "Large Mii Outfit A (Male)",
                                 "Large Mii Outfit A (Female)",
                                 "Large Mii Outfit B (Male)",
                                 "Large Mii Outfit B (Female)",
                                 "Large Mii Outfit C (Male)",
                                 "Large Mii Outfit C (Female)",
                                 "Medium Mii",
                                 "Small Mii",
                                 "Large Mii",
                                 "Peach Biker Outfit",
                                 "Daisy Biker Outfit",
                                 "Rosalina Biker Outfit"};

const char *controller_table[] = {"Wii Wheel", "Nunchuck", "Classic", "GameCube", "USB Controller"};

const char *country_table[] = {"[BAD VALUE]",
                               "Japan",
                               "Antarctica",
                               "Caribbean Netherlands",
                               "Falkland Islands",
                               "Scotland",
                               "Wales",
                               "Sint Maarten",
                               "Anguilla",
                               "Antigua and Barbuda",
                               "Argentina",
                               "Aruba",
                               "Bahamas",
                               "Barbados",
                               "Belize",
                               "Bolivia",
                               "Brazil",
                               "British Virgin Islands",
                               "Canada",
                               "Cayman Islands",
                               "Chile",
                               "Colombia",
                               "Costa Rica",
                               "Dominica",
                               "Dominican Republic",
                               "Ecuador",
                               "El Salvador",
                               "French Guiana",
                               "Grenada",
                               "Guadeloupe",
                               "Guatemala",
                               "Guyana",
                               "Haiti",
                               "Honduras",
                               "Jamaica",
                               "Martinique",
                               "Mexico",
                               "Montserrat",
                               "Curaçao",
                               "Nicaragua",
                               "Panama",
                               "Paraguay",
                               "Peru",
                               "St. Kitts and Nevis",
                               "St. Lucia",
                               "St. Vincent and the Grenadines",
                               "Suriname",
                               "Trinidad and Tobago",
                               "Turks and Caicos Islands",
                               "United States",
                               "Uruguay",
                               "US Virgin Islands",
                               "Venezuela",
                               "Armenia",
                               "Belarus",
                               "Georgia",
                               "Kosovo",
                               "Abkhazia",
                               "Artsakh",
                               "Northern Cyprus",
                               "South Ossetia",
                               "Transnistria",
                               "Åland",
                               "Faroe Islands",
                               "Albania",
                               "Australia",
                               "Austria",
                               "Belgium",
                               "Bosnia & Herzegovina",
                               "Botswana",
                               "Bulgaria",
                               "Croatia",
                               "Cyprus",
                               "Czechia",
                               "Denmark",
                               "Estonia",
                               "Finland",
                               "France",
                               "Germany",
                               "Greece",
                               "Hungary",
                               "Iceland",
                               "Ireland",
                               "Italy",
                               "Latvia",
                               "Lesotho",
                               "Liechtenstein",
                               "Lithuania",
                               "Luxembourg",
                               "North Macedonia",
                               "Malta",
                               "Montenegro",
                               "Mozambique",
                               "Namibia",
                               "Netherlands",
                               "New Zealand",
                               "Norway",
                               "Poland",
                               "Portugal",
                               "Romania",
                               "Russia",
                               "Serbia",
                               "Slovakia",
                               "Slovenia",
                               "South Africa",
                               "Spain",
                               "Eswatini",
                               "Sweden",
                               "Switzerland",
                               "Turkey",
                               "United Kingdom",
                               "Zambia",
                               "Zimbabwe",
                               "Azerbaijan",
                               "Mauritania",
                               "Mali",
                               "Niger",
                               "Chad",
                               "Sudan",
                               "Eritrea",
                               "Djibouti",
                               "Somalia",
                               "Andorra",
                               "Gibraltar",
                               "Guernsey",
                               "Isle of Man",
                               "Jersey",
                               "Monaco",
                               "Taiwan",
                               "Cambodia",
                               "Laos",
                               "Mongolia",
                               "Myanmar",
                               "Nepal",
                               "Vietnam",
                               "North Korea",
                               "South Korea",
                               "Bangladesh",
                               "Bhutan",
                               "Brunei",
                               "Maldives",
                               "Sri Lanka",
                               "Timor-Leste",
                               "British Indian Ocean Territory",
                               "Hong Kong",
                               "Macao",
                               "Cook Islands",
                               "Niue",
                               "Norfolk Island",
                               "Northern Mariana Islands",
                               "American Samoa",
                               "Guam",
                               "Indonesia",
                               "Singapore",
                               "Thailand",
                               "Philippines",
                               "Malaysia",
                               "Saint Barthélemy",
                               "Saint Martin",
                               "Saint Pierre and Miquelon",
                               "China",
                               "Afghanistan",
                               "Kazakhstan",
                               "Kyrgyzstan",
                               "Pakistan",
                               "Tajikistan",
                               "Turkmenistan",
                               "Uzbekistan",
                               "U.A.E",
                               "India",
                               "Egypt",
                               "Oman",
                               "Qatar",
                               "Kuwait",
                               "Saudi Arabia",
                               "Syria",
                               "Bahrain",
                               "Jordan",
                               "Iran",
                               "Iraq",
                               "Israel",
                               "Lebanon",
                               "Palestine",
                               "Yemen",
                               "San Marino",
                               "Vatican City",
                               "Bermuda",
                               "French Polynesia",
                               "Réunion",
                               "Mayotte",
                               "New Caledonia",
                               "Wallis and Futuna",
                               "Nigeria",
                               "Angola",
                               "Ghana",
                               "Togo",
                               "Benin",
                               "Burkina Faso",
                               "Côte d'Ivoire",
                               "Liberia",
                               "Sierra Leone",
                               "Guinea",
                               "Guinea-Bissau",
                               "Senegal",
                               "The Gambia",
                               "Cape Verde",
                               "Saint Helena, Ascension and Tristan da Cunha",
                               "Moldova",
                               "Ukraine",
                               "Cameroon",
                               "Central African Republic",
                               "Democratic Republic of the Congo",
                               "Republic of the Congo",
                               "Equatorial Guinea",
                               "Gabon",
                               "São Tomé and Príncipe",
                               "Algeria",
                               "Ethiopia",
                               "Libya",
                               "Morocco",
                               "South Sudan",
                               "Tunisia",
                               "Sahrawi Arab Democratic Republic",
                               "Cuba",
                               "Burundi",
                               "Comoros",
                               "Kenya",
                               "Madagascar",
                               "Malawi",
                               "Mauritius",
                               "Rwanda",
                               "Seychelles",
                               "Tanzania",
                               "Uganda",
                               "French Southern and Antarctic Lands",
                               "Pitcairn Islands",
                               "British Antarctic Territory",
                               "South Georgia and the South Sandwich Islands",
                               "Federated States of Micronesia",
                               "Fiji",
                               "Kiribati",
                               "Marshall Islands",
                               "Nauru",
                               "Palau",
                               "Papua New Guinea",
                               "Samoa",
                               "Solomon Islands",
                               "Tokelau",
                               "Tonga",
                               "Tuvalu",
                               "Vanuatu",
                               "Christmas Island",
                               "Cocos (Keeling) Islands",
                               "Puerto Rico",
                               "Greenland",
                               "Unknown"};
